name: river-projects
services:
- name: backend
  source_dir: backend
  dockerfile_path: Dockerfile
  http_port: 3001
- name: frontend
  source_dir: frontend
  dockerfile_path: Dockerfile
  http_port: 3000
databases:
- name: postgis-db
  engine: PG